import { Injectable, ValidationPipe } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { v1 as uuid } from 'uuid';
import { Ingredient } from '../entities/ingredient.entity';
import { Repository } from 'typeorm';
import { DessertCategory } from '../entities/dessert.category.entity';

@Injectable()
export class InitRepository {
  constructor(
    @InjectRepository(Ingredient) private ingredient: Repository<Ingredient>,
    @InjectRepository(DessertCategory) private dessertCategory: Repository<DessertCategory>,
  ) {}

  async insertIngredient() {
    const ingreList = ['과일', '견과류', '채소/향신료', '초콜릿/캐러맬', '커피/차/시럽류', '크림/치즈/유제품', '기타'];
    const ingreCount = await this.ingredient.count();
    if (ingreCount < ingreList.length) {
      const entities = ingreList.map((name) => this.ingredient.create({ ingredientName: name, usable: true }));
      await this.ingredient.save(entities); // insert() 대신 save() 사용 - 초기에 스키마 생성되지 않는 문제
    }
  }
  async insertDessertCategory() {
    const firstDessertList = [
      { dessertName: '겨울디저트', sessionNum: 1, sortNum: 1 },
      { dessertName: '구움과자', sessionNum: 1, sortNum: 2 },
      { dessertName: '도넛', sessionNum: 1, sortNum: 3 },
      { dessertName: '떡', sessionNum: 1, sortNum: 4 },
      { dessertName: '마카롱', sessionNum: 1, sortNum: 5 },
      { dessertName: '빵', sessionNum: 1, sortNum: 6 },
      { dessertName: '과일디저트', sessionNum: 1, sortNum: 7 },
      { dessertName: '여름디저트', sessionNum: 1, sortNum: 8 },
      { dessertName: '요거트', sessionNum: 1, sortNum: 9 },
      { dessertName: '전통디저트', sessionNum: 1, sortNum: 10 },
      { dessertName: '초콜릿', sessionNum: 1, sortNum: 11 },
      { dessertName: '케이크', sessionNum: 1, sortNum: 12 },
      { dessertName: '쿠키', sessionNum: 1, sortNum: 13 },
      { dessertName: '타르트/파이', sessionNum: 1, sortNum: 14 },
      { dessertName: '팬케이크', sessionNum: 1, sortNum: 15 },
      { dessertName: '페이스트리', sessionNum: 1, sortNum: 16 },
      { dessertName: '푸딩,젤리', sessionNum: 1, sortNum: 17 },
      { dessertName: '길거리디저트', sessionNum: 1, sortNum: 18 },
      { dessertName: '해외디저트', sessionNum: 1, sortNum: 19 },
      { dessertName: '낯선디저트', sessionNum: 1, sortNum: 20 },
      { dessertName: '기타', sessionNum: 1, sortNum: 21 },
    ];
    /**
         
     const firstDessertList = [
      { dessertCategoryId: 1, dessertName: '겨울디저트', sessionNum: 1, sortNum: 1 },
      { dessertCategoryId: 2, dessertName: '구움과자', sessionNum: 1, sortNum: 2 },
      { dessertCategoryId: 3, dessertName: '도넛', sessionNum: 1, sortNum: 3 },
      { dessertCategoryId: 4, dessertName: '떡', sessionNum: 1, sortNum: 4 },
      { dessertCategoryId: 5, dessertName: '마카롱', sessionNum: 1, sortNum: 5 },
      { dessertCategoryId: 6, dessertName: '빵', sessionNum: 1, sortNum: 6 },
      { dessertCategoryId: 7, dessertName: '과일디저트', sessionNum: 1, sortNum: 7 },
      { dessertCategoryId: 8, dessertName: '여름디저트', sessionNum: 1, sortNum: 8 },
      { dessertCategoryId: 9, dessertName: '요거트', sessionNum: 1, sortNum: 9 },
      { dessertCategoryId: 10, dessertName: '전통디저트', sessionNum: 1, sortNum: 10 },
      { dessertCategoryId: 11, dessertName: '초콜릿', sessionNum: 1, sortNum: 11 },
      { dessertCategoryId: 12, dessertName: '케이크', sessionNum: 1, sortNum: 12 },
      { dessertCategoryId: 13, dessertName: '쿠키', sessionNum: 1, sortNum: 13 },
      { dessertCategoryId: 14, dessertName: '타르트/파이', sessionNum: 1, sortNum: 14 },
      { dessertCategoryId: 15, dessertName: '팬케이크', sessionNum: 1, sortNum: 15 },
      { dessertCategoryId: 16, dessertName: '페이스트리', sessionNum: 1, sortNum: 16 },
      { dessertCategoryId: 17, dessertName: '푸딩,젤리', sessionNum: 1, sortNum: 17 },
      { dessertCategoryId: 18, dessertName: '길거리디저트', sessionNum: 1, sortNum: 18 },
      { dessertCategoryId: 19, dessertName: '해외디저트', sessionNum: 1, sortNum: 19 },
      { dessertCategoryId: 20, dessertName: '낯선디저트', sessionNum: 1, sortNum: 20 },
      { dessertCategoryId: 21, dessertName: '기타', sessionNum: 1, sortNum: 21 },
    ];
     */
    const secondDessertList = [
      { dessertName: '계란빵', parentDCId: 1, sessionNum: 2, sortNum: 22 },
      { dessertName: '국화빵', parentDCId: 1, sessionNum: 2, sortNum: 23 },
      { dessertName: '군고구마', parentDCId: 1, sessionNum: 2, sortNum: 24 },
      { dessertName: '땅콩빵', parentDCId: 1, sessionNum: 2, sortNum: 25 },
      { dessertName: '붕어빵', parentDCId: 1, sessionNum: 2, sortNum: 26 },
      { dessertName: '찐감자', parentDCId: 1, sessionNum: 2, sortNum: 27 },
      { dessertName: '찐빵/호빵', parentDCId: 1, sessionNum: 2, sortNum: 28 },
      { dessertName: '풀빵', parentDCId: 1, sessionNum: 2, sortNum: 29 },
      { dessertName: '호떡', parentDCId: 1, sessionNum: 2, sortNum: 30 },
      { dessertName: '까눌레', parentDCId: 2, sessionNum: 2, sortNum: 31 },
      { dessertName: '다쿠아즈', parentDCId: 2, sessionNum: 2, sortNum: 32 },
      { dessertName: '마들렌', parentDCId: 2, sessionNum: 2, sortNum: 33 },
      { dessertName: '머핀', parentDCId: 2, sessionNum: 2, sortNum: 34 },
      { dessertName: '버터바', parentDCId: 2, sessionNum: 2, sortNum: 35 },
      { dessertName: '브라우니', parentDCId: 2, sessionNum: 2, sortNum: 36 },
      { dessertName: '스콘', parentDCId: 2, sessionNum: 2, sortNum: 37 },
      { dessertName: '컵케이크', parentDCId: 2, sessionNum: 2, sortNum: 38 },
      { dessertName: '퀸아망', parentDCId: 2, sessionNum: 2, sortNum: 39 },
      { dessertName: '파운드케이크', parentDCId: 2, sessionNum: 2, sortNum: 40 },
      { dessertName: '휘낭시에', parentDCId: 2, sessionNum: 2, sortNum: 41 },
      { dessertName: '꽈배기', parentDCId: 3, sessionNum: 2, sortNum: 42 },
      { dessertName: '도넛', parentDCId: 3, sessionNum: 2, sortNum: 43 },
      { dessertName: '도넛홀/먼치킨', parentDCId: 3, sessionNum: 2, sortNum: 44 },
      { dessertName: '찹쌀도넛', parentDCId: 3, sessionNum: 2, sortNum: 45 },
      { dessertName: '폰데링/츄이스티', parentDCId: 3, sessionNum: 2, sortNum: 46 },
      { dessertName: '꿀떡', parentDCId: 4, sessionNum: 2, sortNum: 47 },
      { dessertName: '바람떡', parentDCId: 4, sessionNum: 2, sortNum: 48 },
      { dessertName: '시루떡', parentDCId: 4, sessionNum: 2, sortNum: 49 },
      { dessertName: '영양찰떡', parentDCId: 4, sessionNum: 2, sortNum: 50 },
      { dessertName: '꼬끄', parentDCId: 5, sessionNum: 2, sortNum: 51 },
      { dessertName: '뚱카롱', parentDCId: 5, sessionNum: 2, sortNum: 52 },
      { dessertName: '마카롱', parentDCId: 5, sessionNum: 2, sortNum: 53 },
      { dessertName: '구황작물빵', parentDCId: 6, sessionNum: 2, sortNum: 54 },
      { dessertName: '바게트', parentDCId: 6, sessionNum: 2, sortNum: 55 },
      { dessertName: '베이글', parentDCId: 6, sessionNum: 2, sortNum: 56 },
      { dessertName: '소금빵', parentDCId: 6, sessionNum: 2, sortNum: 57 },
      { dessertName: '식빵', parentDCId: 6, sessionNum: 2, sortNum: 58 },
      { dessertName: '카스테라', parentDCId: 6, sessionNum: 2, sortNum: 59 },
      { dessertName: '캄파뉴', parentDCId: 6, sessionNum: 2, sortNum: 60 },
      { dessertName: '팡도르', parentDCId: 6, sessionNum: 2, sortNum: 61 },
      { dessertName: '크림빵', parentDCId: 6, sessionNum: 2, sortNum: 62 },
      { dessertName: '포카치아', parentDCId: 6, sessionNum: 2, sortNum: 63 },
      { dessertName: '사워도우', parentDCId: 6, sessionNum: 2, sortNum: 64 },
      { dessertName: '루스틱', parentDCId: 6, sessionNum: 2, sortNum: 65 },
      { dessertName: '뺑오쇼콜라', parentDCId: 6, sessionNum: 2, sortNum: 66 },
      { dessertName: '시나몬롤', parentDCId: 6, sessionNum: 2, sortNum: 67 },
      { dessertName: '치아바타', parentDCId: 6, sessionNum: 2, sortNum: 68 },
      { dessertName: '프레첼', parentDCId: 6, sessionNum: 2, sortNum: 69 },
      { dessertName: '과일컵', parentDCId: 7, sessionNum: 2, sortNum: 70 },
      { dessertName: '탕후루', parentDCId: 7, sessionNum: 2, sortNum: 71 },
      { dessertName: '후루츠산도', parentDCId: 7, sessionNum: 2, sortNum: 72 },
      { dessertName: '빙수	', parentDCId: 8, sessionNum: 2, sortNum: 73 },
      { dessertName: '셔벗', parentDCId: 8, sessionNum: 2, sortNum: 74 },
      { dessertName: '아이스바', parentDCId: 8, sessionNum: 2, sortNum: 75 },
      { dessertName: '아이스크림', parentDCId: 8, sessionNum: 2, sortNum: 76 },
      { dessertName: '젤라또', parentDCId: 8, sessionNum: 2, sortNum: 77 },
      { dessertName: '아이스크림케이크', parentDCId: 8, sessionNum: 2, sortNum: 78 },
      { dessertName: '요거트', parentDCId: 9, sessionNum: 2, sortNum: 79 },
      { dessertName: '개성주악', parentDCId: 10, sessionNum: 2, sortNum: 80 },
      { dessertName: '달고나', parentDCId: 10, sessionNum: 2, sortNum: 81 },
      { dessertName: '약과', parentDCId: 10, sessionNum: 2, sortNum: 82 },
      { dessertName: '양갱', parentDCId: 10, sessionNum: 2, sortNum: 83 },
      { dessertName: '엿', parentDCId: 10, sessionNum: 2, sortNum: 84 },
      { dessertName: '유과', parentDCId: 10, sessionNum: 2, sortNum: 85 },
      { dessertName: '누룽지', parentDCId: 10, sessionNum: 2, sortNum: 86 },
      { dessertName: '쫀디기', parentDCId: 10, sessionNum: 2, sortNum: 87 },
      { dessertName: '오란다', parentDCId: 10, sessionNum: 2, sortNum: 88 },
      { dessertName: '강정', parentDCId: 10, sessionNum: 2, sortNum: 89 },
      { dessertName: '정과', parentDCId: 10, sessionNum: 2, sortNum: 90 },
      { dessertName: '다크초콜릿', parentDCId: 11, sessionNum: 2, sortNum: 91 },
      { dessertName: '루비초콜릿', parentDCId: 11, sessionNum: 2, sortNum: 92 },
      { dessertName: '밀크초콜릿', parentDCId: 11, sessionNum: 2, sortNum: 93 },
      { dessertName: '화이트초콜릿', parentDCId: 11, sessionNum: 2, sortNum: 94 },
      { dessertName: '두바이초콜릿', parentDCId: 11, sessionNum: 2, sortNum: 95 },
      { dessertName: '롤케이크', parentDCId: 12, sessionNum: 2, sortNum: 96 },
      { dessertName: '몽블랑', parentDCId: 12, sessionNum: 2, sortNum: 97 },
      { dessertName: '케이크', parentDCId: 12, sessionNum: 2, sortNum: 98 },
      { dessertName: '티라미수', parentDCId: 12, sessionNum: 2, sortNum: 99 },
      { dessertName: '치즈케이크', parentDCId: 12, sessionNum: 2, sortNum: 100 },
      { dessertName: '케이크팝', parentDCId: 12, sessionNum: 2, sortNum: 101 },
      { dessertName: '크레이프케이크', parentDCId: 12, sessionNum: 2, sortNum: 102 },
      { dessertName: '랑그드샤', parentDCId: 13, sessionNum: 2, sortNum: 103 },
      { dessertName: '르뱅쿠키', parentDCId: 13, sessionNum: 2, sortNum: 104 },
      { dessertName: '머랭쿠키', parentDCId: 13, sessionNum: 2, sortNum: 105 },
      { dessertName: '청크쿠키', parentDCId: 13, sessionNum: 2, sortNum: 106 },
      { dessertName: '쿠키도우', parentDCId: 13, sessionNum: 2, sortNum: 107 },
      { dessertName: '사브레', parentDCId: 13, sessionNum: 2, sortNum: 108 },
      { dessertName: '비스코티', parentDCId: 13, sessionNum: 2, sortNum: 109 },
      { dessertName: '상투과자', parentDCId: 13, sessionNum: 2, sortNum: 110 },
      { dessertName: '타르트', parentDCId: 14, sessionNum: 2, sortNum: 111 },
      { dessertName: '파이', parentDCId: 14, sessionNum: 2, sortNum: 112 },
      { dessertName: '수플레', parentDCId: 15, sessionNum: 2, sortNum: 113 },
      { dessertName: '와플', parentDCId: 15, sessionNum: 2, sortNum: 114 },
      { dessertName: '크레페', parentDCId: 15, sessionNum: 2, sortNum: 115 },
      { dessertName: '팬케이크', parentDCId: 15, sessionNum: 2, sortNum: 116 },
      { dessertName: '밀푀유', parentDCId: 16, sessionNum: 2, sortNum: 117 },
      { dessertName: '빨미까레', parentDCId: 16, sessionNum: 2, sortNum: 118 },
      { dessertName: '슈', parentDCId: 16, sessionNum: 2, sortNum: 119 },
      { dessertName: '에클레어', parentDCId: 16, sessionNum: 2, sortNum: 120 },
      { dessertName: '크루아상', parentDCId: 16, sessionNum: 2, sortNum: 121 },
      { dessertName: '크룽지', parentDCId: 16, sessionNum: 2, sortNum: 122 },
      { dessertName: '페이스트리', parentDCId: 16, sessionNum: 2, sortNum: 123 },
      { dessertName: '젤리', parentDCId: 17, sessionNum: 2, sortNum: 124 },
      { dessertName: '푸딩', parentDCId: 17, sessionNum: 2, sortNum: 125 },
      { dessertName: '브레드푸딩', parentDCId: 17, sessionNum: 2, sortNum: 126 },
      { dessertName: '소떡소떡', parentDCId: 18, sessionNum: 2, sortNum: 127 },
      { dessertName: '소시지', parentDCId: 18, sessionNum: 2, sortNum: 128 },
      { dessertName: '솜사탕', parentDCId: 18, sessionNum: 2, sortNum: 129 },
      { dessertName: '추로스', parentDCId: 18, sessionNum: 2, sortNum: 130 },
      { dessertName: '핫도그', parentDCId: 18, sessionNum: 2, sortNum: 131 },
      { dessertName: '회오리감자', parentDCId: 18, sessionNum: 2, sortNum: 132 },
      { dessertName: '델리만쥬', parentDCId: 18, sessionNum: 2, sortNum: 133 },
      { dessertName: '누가크래커', parentDCId: 19, sessionNum: 2, sortNum: 134 },
      { dessertName: '당고', parentDCId: 19, sessionNum: 2, sortNum: 135 },
      { dessertName: '모찌', parentDCId: 19, sessionNum: 2, sortNum: 136 },
      { dessertName: '카이막', parentDCId: 19, sessionNum: 2, sortNum: 137 },
      { dessertName: '타코야끼', parentDCId: 19, sessionNum: 2, sortNum: 138 },
      { dessertName: '화과자', parentDCId: 19, sessionNum: 2, sortNum: 139 },
      { dessertName: '사치마', parentDCId: 19, sessionNum: 2, sortNum: 140 },
      { dessertName: '센베', parentDCId: 19, sessionNum: 2, sortNum: 141 },
      { dessertName: '도라야키', parentDCId: 19, sessionNum: 2, sortNum: 142 },
      { dessertName: '바클라바', parentDCId: 19, sessionNum: 2, sortNum: 143 },
      { dessertName: '구겔호프', parentDCId: 20, sessionNum: 2, sortNum: 144 },
      { dessertName: '그라니타', parentDCId: 20, sessionNum: 2, sortNum: 145 },
      { dessertName: '래밍턴', parentDCId: 20, sessionNum: 2, sortNum: 146 },
      { dessertName: '바움쿠헨', parentDCId: 20, sessionNum: 2, sortNum: 147 },
      { dessertName: '베녜', parentDCId: 20, sessionNum: 2, sortNum: 148 },
      { dessertName: '베린느', parentDCId: 20, sessionNum: 2, sortNum: 149 },
      { dessertName: '브리오슈', parentDCId: 20, sessionNum: 2, sortNum: 150 },
      { dessertName: '카사타', parentDCId: 20, sessionNum: 2, sortNum: 151 },
      { dessertName: '슈톨렌', parentDCId: 20, sessionNum: 2, sortNum: 152 },
      { dessertName: '테린느', parentDCId: 20, sessionNum: 2, sortNum: 153 },
      { dessertName: '티그레', parentDCId: 20, sessionNum: 2, sortNum: 154 },
      { dessertName: '슈니발렌', parentDCId: 20, sessionNum: 2, sortNum: 155 },
      { dessertName: '판나코타', parentDCId: 20, sessionNum: 2, sortNum: 156 },
      { dessertName: '플람베', parentDCId: 20, sessionNum: 2, sortNum: 157 },
      { dessertName: '파블로바', parentDCId: 20, sessionNum: 2, sortNum: 158 },
      { dessertName: '기타', parentDCId: 21, sessionNum: 2, sortNum: 159 },
    ];
    const firDcCount = await this.dessertCategory.count();
    if (firDcCount < firstDessertList.length) {
      const entities = firstDessertList.map((item) => this.dessertCategory.create(item));
      await this.dessertCategory.save(entities); // insert() 대신 save() 사용
    }
    const secDcCount = await this.dessertCategory.count();
    if (secDcCount < secondDessertList.length) {
      const entities = secondDessertList.map((item) => this.dessertCategory.create(item));
      await this.dessertCategory.save(entities); // insert() 대신 save() 사용
    }
  }
}
